files:
  include: src/scss/
options:
  formatter: stylish
  merge-default-rules: false
rules:
  bem-depth:
    - 0
    - max-depth: 1
  class-name-format:
    - 1
    - convention: hyphenatedbem
  empty-line-between-blocks: 0
  id-name-format:
    - 1
    - convention: hyphenatedbem
  indentation:
    - 0
    - size: 1
  no-color-literals: 0
  no-extends: 1
  no-trailing-zero: 1
  no-transition-all: 1
  placeholder-name-format:
    - 1
    - convention: hyphenatedbem
  property-sort-order:
    - 1
    - order: smacss
  quotes:
    - 1
    - style: double