# Site settings
title: Pattern library
email: your-email@domain.com
description: Things. 
baseurl: "" # the subpath of the pattern library, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol of the pattern library

# Collections
collections: 
  patterns:
    output: true
    permalink: /:title/

# Build settings
markdown: kramdown
destination: ../pattern-library